// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCROp97Wh7Pf2qzuVPV4YidsXa46QedBwM',
    appId: '1:942341223041:web:4e6707e459dfbc225e1380',
    messagingSenderId: '942341223041',
    projectId: 'shopapp-getx-00',
    authDomain: 'shopapp-getx-00.firebaseapp.com',
    storageBucket: 'shopapp-getx-00.appspot.com',
    measurementId: 'G-80PMHQKR27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26rcK5mabDV2f7LLVzhU7oGv9PKXJUM4',
    appId: '1:942341223041:android:9b5a5f10e32a4fdd5e1380',
    messagingSenderId: '942341223041',
    projectId: 'shopapp-getx-00',
    storageBucket: 'shopapp-getx-00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSyUwheoI5HVjQljJxbwhaSJ2vAELrbJk',
    appId: '1:942341223041:ios:db6c466906aa7a5a5e1380',
    messagingSenderId: '942341223041',
    projectId: 'shopapp-getx-00',
    storageBucket: 'shopapp-getx-00.appspot.com',
    iosClientId: '942341223041-rjvg6deu9j7346v3vgtdq86s0332con9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSyUwheoI5HVjQljJxbwhaSJ2vAELrbJk',
    appId: '1:942341223041:ios:db6c466906aa7a5a5e1380',
    messagingSenderId: '942341223041',
    projectId: 'shopapp-getx-00',
    storageBucket: 'shopapp-getx-00.appspot.com',
    iosClientId: '942341223041-rjvg6deu9j7346v3vgtdq86s0332con9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );
}
